SET NAMES UTF8;
DROP DATABASE IF EXISTS blogs;
CREATE DATABASE blogs CHARSET=UTF8;
USE blogs;

CREATE TABLE dept(
    uid INT PRIMARY KEY AUTO_INCREMENT,
    uname VARCHAR(32),
    ulinkman VARCHAR(32),
    ucontent VARCHAR(65533),
    utime VARCHAR(32)
);

